const datacollage = {
    cardData:[
        {
            id:1,
            img:"/img/Ldrp.jpg",
            text:"LDRP - Institute of Technology and Research",
            text2:"Principle :",
            text3:"Gargi Ragpara",
            text4:"Email :",
            text5:"Principle@ldrp.ac.in",
            text6:"Mentoring remaining",
            style:" w-[5.3rem] ",
            path:"/principle",
            border:" border-l-[5px] border-[#F00]",
            textbg:" text-[#F00]",
        },
        {
            id:2,
            img:"/img/Vs.png",
            text:"VS - Institute Of Technology and Research",
            text2:"Principle :",
            text3:"Gargi Ragpara",
            text4:"Email :",
            text5:"Principle@ldrp.ac.in",
            text6:"Mentoring remaining",
            link:"/conversion2",
            style:" w-[5.3rem] ",
            border:" border-l-[5px] border-[#00C313]",
            textbg:" text-[#00C313]",

        },
        {
            id:3,
            img:"/img/Smmp.svg",
            text:"SMMP - Institute of Technology and Research",
            text2:"Principle :",
            text3:"Gargi Ragpara",
            text4:"Email :",
            text5:"Principle@ldrp.ac.in",
            text6:"Mentoring remaining",
            link:"/conversion3",
            border:" border-l-[5px] border-[#FFC700]",
            textbg:" text-[#FFC700]",
        },
        {
            id:4,
            img:"/img/Cm.svg",
            text:"CM Patel College of Physiotherapy",
            text2:"Principle :",
            text3:"Gargi Ragpara",
            text4:"Email :",
            text5:"Principle@ldrp.ac.in",
            text6:"Mentoring remaining",
            link:"/conversion4",
            border:" border-l-[5px] border-[#F00]",
            textbg:" text-[#F00]",
        },
        {
            id:5,
            img:"/img/Vpmp.svg",
            text:"VPMP Polytechnic",
            text2:"Principle :",
            text3:"Gargi Ragpara",
            text4:"Email :",
            text5:"Principle@ldrp.ac.in",
            text6:"Mentoring remaining",
            link:"/conversion5",
            border:" border-l-[5px] border-[#F00]",
            textbg:" text-[#F00]",
        },
        {
            id:6,
            img:"/img/Sk.svg",
            text:"S.K.Patel - Institute of Management & Research",
            text2:"Principle :",
            text3:"Gargi Ragpara",
            text4:"Email :",
            text5:"Principle@ldrp.ac.in",
            text6:"Mentoring remaining",
            link:"/conversion5",
            border:" border-l-[5px] border-[#F00]",
            textbg:" text-[#F00]",
        }
    ]
}
export default datacollage;